FROM node

#RUN mkdir /src
# Create app directory
WORKDIR /src

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN yarn install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY ./ /src

ENV MONGO_USER=user
ENV MONGO_PW=password

EXPOSE 8080
CMD [ "yarn", "start-data-storage" ]