#!/bin/bash

clear

echo "Cleaning up mongo containers"
docker rm -f mongo-vehicle
echo "Starting mongoDB..."
docker pull mongo
docker run --name mongo-vehicle --restart=always -d -p 27017:27017 mongo mongod --auth
echo "Configuring mongo auth into mongo-vehicle docker"
sudo docker exec -i -t mongo-vehicle bash
mongo
use admin
db.createUser({user:"root",pwd:"1234",roles:[{role:"root",db:"admin"}]})
echo "creating vehicle database..."
use vehicle
echo "vehicle database was created"
exit
exit
mongo -u "root" -p "1234" localhost --authenticationDatabase "admin"
echo "authentication setup done"
echo "mongoDB was running"
